INSERT INTO category (category_name) VALUES
				("Popular Science"),
				("Information Security"),
				("Programming"),
				("Game Development"),
				("Website Development"),
				("Algorithms"),
				("Open Source"),
				("DevOps"),
				("Games"),
				("Golang"),
				("Python"),
				("Rust"),
				("JavaScript"),
				("Java"),
				("C"),
				("C++"),
				("C#"),
				("Kotlin");